export const weatherData = [
  {
    id: 1,
    city: "Warszawa",
    temp: 18,
    condition: "Słonecznie",
    clouds: 10,
    windSpeed: 15, 
    windDir: "NW",
    precipProb: 0,
    precipAmount: 0,
    forecast: [
      { day: "Poniedziałek", temp: 19, condition: "Słonecznie" },
      { day: "Wtorek", temp: 20, condition: "Częściowe zachm." },
      { day: "Środa", temp: 17, condition: "Deszcz" },
      { day: "Czwartek", temp: 16, condition: "Deszcz" },
      { day: "Piątek", temp: 18, condition: "Pochmurno" },
    ],
  },
  {
    id: 2,
    city: "Kraków",
    temp: 14,
    condition: "Deszcz",
    clouds: 90,
    windSpeed: 10,
    windDir: "W",
    precipProb: 80,
    precipAmount: 5.2,
    forecast: [
      { day: "Poniedziałek", temp: 15, condition: "Deszcz" },
      { day: "Wtorek", temp: 16, condition: "Pochmurno" },
      { day: "Środa", temp: 18, condition: "Słonecznie" },
      { day: "Czwartek", temp: 19, condition: "Słonecznie" },
      { day: "Piątek", temp: 20, condition: "Burza" },
    ],
  },
  {
    id: 3,
    city: "Gdańsk",
    temp: 12,
    condition: "Wietrznie",
    clouds: 60,
    windSpeed: 45,
    windDir: "N",
    precipProb: 20,
    precipAmount: 0,
    forecast: [
      { day: "Poniedziałek", temp: 13, condition: "Pochmurno" },
      { day: "Wtorek", temp: 14, condition: "Wietrznie" },
      { day: "Środa", temp: 12, condition: "Deszcz" },
      { day: "Czwartek", temp: 11, condition: "Deszcz" },
      { day: "Piątek", temp: 13, condition: "Słonecznie" },
    ],
  },
  {
    id: 4,
    city: "Wrocław",
    temp: 22,
    condition: "Burza",
    clouds: 85,
    windSpeed: 25,
    windDir: "SW",
    precipProb: 95,
    precipAmount: 12.5,
    forecast: [
      { day: "Poniedziałek", temp: 20, condition: "Deszcz" },
      { day: "Wtorek", temp: 18, condition: "Burza" },
      { day: "Środa", temp: 21, condition: "Pochmurno" },
      { day: "Czwartek", temp: 23, condition: "Słonecznie" },
      { day: "Piątek", temp: 24, condition: "Słonecznie" },
    ],
  },
  {
    id: 5,
    city: "Zakopane",
    temp: 5,
    condition: "Śnieg",
    clouds: 100,
    windSpeed: 5,
    windDir: "S",
    precipProb: 100,
    precipAmount: 8.0,
    forecast: [
      { day: "Poniedziałek", temp: 4, condition: "Śnieg" },
      { day: "Wtorek", temp: 2, condition: "Śnieg" },
      { day: "Środa", temp: -1, condition: "Mróz" },
      { day: "Czwartek", temp: 0, condition: "Zachmurzenie" },
      { day: "Piątek", temp: 3, condition: "Słonecznie" },
    ],
  },
];